Feature/UI
maosan132/Magic-bookstore pull request #5
Opened 2021-09-08 23:15 UTC by maosan132

Hello Reviewers, Please give my code a shot and give me suggestions for improvement, I would appreciate it so much. It encompasses milestone 5 of the Bookstore project.

- [ ] The full design specs in this Zeplin project. 
- [ ] Implement the styling of the different components based on the design.

2021-09-08 23:32 UTC, rukundoeric requested changes
Hi guys, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] The live-demo in your README is for a different project. kindly replace it with the correct one.
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-09-08 23:32 UTC, rukundoeric commented on src/containers/BooksList.js
> +      </header>
- [ ] <b>REQUIRED:</b> To make sure that your codebase is always clean, remember to remove commented-codes.

2021-09-08 23:32 UTC, rukundoeric commented on src/styles/App.css
> +}
- [ ] <b>REQUIRED:</b> Your app doesn't look exactly like mockup design

| Original      | Yours |
  | ----------- | ----------- |
| ![80047697-0c3f6280-8506-11ea-9416-a4f1800e2329](https://user-images.githubusercontent.com/45217364/130871998-88863e2f-c823-4b7b-a5c4-20162973ff21.png) | ![scrnli_9_9_2021_1-22-23 AM](https://user-images.githubusercontent.com/45217364/132598367-05da91b8-2703-44f5-93e8-c0bf29061b08.png) |
   - The a circle progress bar missing on each of your book item. 
   -  Around each of your Action buttons, there some dots which are not present in the mockup design, kindly remove them.

2021-09-09 15:01 UTC, maosan132 commented on src/containers/BooksList.js
> +      </header>
DOne, thanks

2021-09-09 16:28 UTC, rukundoeric approved these changes
Hi @maosan132,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------

2021-09-09 18:22 UTC, merged